movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name='movieapp'
urlpatterns = [

    path('',views.demo,name='demo'),


    path('movie/<int:movieid>/',views.detail,name='detail'),
    path('add/',views.addmov,name='addmov'),
    path('edit/<int:id>/',views.update,name='update'),
path('del/<int:id>/',views.delete,name='delete')

    ]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                       document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name= models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class movform(forms.ModelForm):
    class Meta:
        model= Movie
        fields=['name','desc','year']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

from .models import Movie
from .forms import movform

# Create your views here.
def demo(request):
    movie=Movie.objects.all()
    context={
        'movielist':movie
    }
    return render(request,'index.html',context)

def detail(request,movieid):
    movie=Movie.objects.get(id=movieid)
    return render(request,"detail.html",{'movie':movie})

def addmov(request):
    if request.method == "POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return  render(request,'add.html')


def update(request,id):
    movie1=Movie.objects.get(id=id)
    form1=movform(request.POST or None, request.FILES,instance=movie1)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':movie1,'form':form1})

def delete(request,id):
    if request.method=="POST":
        movie2=Movie.objects.get(id=id)
        movie2.delete()
        return redirect('/')
    return render(request,'del.html')

movieproject/templates/add.html
{% extends 'basic.html' %}
{% block body%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Movie name"><br>
  <input type="text" name="desc" placeholder="Description"><br>
   <input type="text" name="year" placeholder="Year">
  <input type="file" name="img"><br>
  <input type="submit">
</form>
</body>
</html>

{% endblock %}

movieproject/templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    ONLINE MOVIES
  </a>
</nav>
{% block body%}
{% endblock %}
</body>
</html>

movieproject/templates/del.html
<form method="post">
  {% csrf_token %}
  do you want to delete this movie
  <input type="submit">

</form>

movieproject/templates/detail.html
{% extends 'basic.html' %}
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="450">
        </div>
       <div class="col-md-6">
           <h5>{{movie.name}}</h5>
           <h4>{{movie.desc}}</h4>
           <h6>{{movie.year}}</h6>


           <a class= "btn btn-warning" href="{% url 'movieapp:update' movie.id %}">EDIT</a>
           <a class= "btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
       </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'basic.html' %}
{% add block %}

<form method="post" xmlns="http://www.w3.org/1999/html">
{% csrf_token %}
  {{ form.as_p }}
  <input type="button">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'basic.html' %}
{% block body %}

<div class="container" >
    <div class="row" >
        <div class="card-deck">

        {% for i in movielist %}

        <div class="col-md-3" >
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="250" >
  <div class="card-body">
    <h5 class="Card title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}.</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
        {% endfor %}

        </div>
    </div>

</div>

<!-- {% for i in movielist %}-->
<!--<img src="{{i.img.url}}" width="100" height="100">-->
<!--<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}</a><br>-->
<!--   {% endfor %}&ndash;&gt;-->
<div style="text-align:center">
<a class= "btn btn-danger" href="{% url 'movieapp:addmov'  %}">ADD</a>
</div>
{% endblock %}